//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArenaNet.GuildWars2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArenaNet.GuildWars2.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve build from {0}.
        /// </summary>
        internal static string GetBuildError {
            get {
                return ResourceManager.GetString("GetBuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve color descriptions from {0}.
        /// </summary>
        internal static string GetColorDescriptionsError {
            get {
                return ResourceManager.GetString("GetColorDescriptionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve continent descriptions from {0}.
        /// </summary>
        internal static string GetContinentDescriptionsError {
            get {
                return ResourceManager.GetString("GetContinentDescriptionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve discoveredGameItems from {0}.
        /// </summary>
        internal static string GetDiscoveredGameItemsError {
            get {
                return ResourceManager.GetString("GetDiscoveredGameItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve discovered recipes from {0}.
        /// </summary>
        internal static string GetDiscoveredRecipesError {
            get {
                return ResourceManager.GetString("GetDiscoveredRecipesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve event descriptions from {0}.
        /// </summary>
        internal static string GetEventDescriptionsError {
            get {
                return ResourceManager.GetString("GetEventDescriptionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve event names from {0}.
        /// </summary>
        internal static string GetEventNamesError {
            get {
                return ResourceManager.GetString("GetEventNamesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve events from {0}.
        /// </summary>
        internal static string GetEventsError {
            get {
                return ResourceManager.GetString("GetEventsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve guild from {0}.
        /// </summary>
        internal static string GetGuildError {
            get {
                return ResourceManager.GetString("GetGuildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve item details from {0}.
        /// </summary>
        internal static string GetItemDetailsError {
            get {
                return ResourceManager.GetString("GetItemDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve map descriptions from {0}.
        /// </summary>
        internal static string GetMapDescriptionsError {
            get {
                return ResourceManager.GetString("GetMapDescriptionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve map floor from {0}.
        /// </summary>
        internal static string GetMapFloorError {
            get {
                return ResourceManager.GetString("GetMapFloorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve map names from {0}.
        /// </summary>
        internal static string GetMapNamesError {
            get {
                return ResourceManager.GetString("GetMapNamesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve objective names from {0}.
        /// </summary>
        internal static string GetObjectiveNamesError {
            get {
                return ResourceManager.GetString("GetObjectiveNamesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve recipe details from {0}.
        /// </summary>
        internal static string GetRecipeDetailsError {
            get {
                return ResourceManager.GetString("GetRecipeDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve worlds from {0}.
        /// </summary>
        internal static string GetWorldsError {
            get {
                return ResourceManager.GetString("GetWorldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve world vs worldMatch details from {0}.
        /// </summary>
        internal static string GetWorldVsWorldMatchDetailsError {
            get {
                return ResourceManager.GetString("GetWorldVsWorldMatchDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve world vs world matches from {0}.
        /// </summary>
        internal static string GetWorldVsWorldMatchesError {
            get {
                return ResourceManager.GetString("GetWorldVsWorldMatchesError", resourceCulture);
            }
        }
    }
}
